sudo: required

services:
  - docker

before_install:
  - docker build -t  production_server -f Dockerfile.build .

script:
  - docker run -e CI=true production_server npm run test -- --coverage --passWithNoTests

deploy:
  provider: elasticbeanstalk
  region: "me-south-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-me-south-1-069395571727"
  bucket_path: "Docker"
  on:
   branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  edge: true
