sudo: required

services:
  - docker

before_install:
  - docker build -t  development_server -f Dockerfile.dev .

script:
  - docker run -e CI=true development_server npm run test -- --coverage --passWithNoTests

deploy:
  provider: elasticbeanstalk
  region: "me-south-1"
  app: "web-app"
  env: "Webapp-env"
  bucket_name: "elasticbeanstalk-me-south-1-069395571727"
  bucket_path: "web-app"
  on:
   branch: main
  access_key_id: $userId
  secret_access_key: 
    secure: "$userSecret"
