sudo: required

services:
  - docker

before_install:
  - docker build -t  mostafaemad18697/react-web-app -f Dockerfile.dev .

script:
  - docker run mostafaemad18697/react-web-app npm run test -- --coverage
  